### ISSUE TITLE
Group by namespace

### ISSUE THREAD

**Issue by andresdigiovanni** [lijunle/Vsxmd#55] opened 2018-12-30 10:11 UTC
Group classes by namespace

**Comment by lijunle** [comment] 2019-01-07 15:52
@andresdigiovanni Could you please provide more context about your idea? How do you want the Markdown to be generated?

**Comment by andresdigiovanni** [comment] 2019-01-07 20:14
I think it's much clearer to have the documentation divided into multiple files.

The main page "Home.md" should show the different namespaces and the different classes with their explanation (ex: https://docs.microsoft.com/es-es/dotnet/api/system.collections.generic?view=netframework-4.7.2).

Then, there should be a page for each of the classes, interfaces, etc ... Like this (https://docs.microsoft.com/es-es/dotnet/api/system.collections.generic.queue-1?view=netframework-4.7.2).

Congratulations for the work!

**Comment by lijunle** [comment] 2019-01-08 16:49
@andresdigiovanni Thanks for your explanation!

Do you have a project with lots of classes and methods and each of them have very long summary? How many lines are generated in your Markdown file?

I am not sure if such a full documentation experience is the goal of Vsxmd. The current goal is to extra and represent the XML information to Markdown file because Markdown file is more friendly to human being and supported by various Git providers.

To split one file to separated files, I have the following concerns:

1. Search. Currently, we get free text search functionality from browser and Git providers.
2. Deep link. Although the Markdown deep link is supporting in all Git providers, we need to more experiments.
3. Content density. I am not sure the content is one class/method is worth to be a separated page. If no, people will be tired of jumping files back and ford. (I used to do this when reviewing some MSDN .Net classes/methods.)

.Net project trends to write short summary/example in XML documentation and have separated files for full tutorial/guides. [DocFx](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html) is support such huge project scenario. Separated files will be generated for the tutorial/guide and each classes/methods. Maybe that is you expected behavior?

**Comment by lijunle** [comment] 2019-08-21 00:31
Close this issue because no future work on it.

**Closed by lijunle** 2019-08-21 00:31 UTC

**Comment by mxashlynn** [comment] 2020-04-28 03:37
I just wanted to say thank you for providing the explanation as to why everything is output into a single file.

In my case, I like the idea of producing output as markdown files instead of as HTML (as DocFx does).  However, your explanation of the advantages of keeping everything in one file, and of the differences between this project's goals and DocFx's goals are clear and make sense.

I will think further as to the what makes the most sense for me with my project.

Thanks, too, for creating this wonderful tool!  👏
